### ISSUE TITLE
couldn't post more than one tag

### ISSUE THREAD

**Issue by gitkent** [Aeron/PyFlowdock#4]
Hi, I am trying to usr chat.post to post more than one tags, but it only post the last one in the list. For e.g.
<<<
chat.post(success_message, hostname, ['info','good','ok'])
>>>

it only posted #ok in flowdock chat.

**Comment by Aeron** [comment]
Hey, as you probably noticed, this repo (and project itself) is a bit outdated and currently not maintained in any way 😃 At least since I stopped using Flowdock. So I’m not sure if Flowdock API has been changed since last time I saw it, maybe it is and that can cause such troubles.

I can’t promise you that I’ll get back to this project any time soon or at all. But you’re always free to fork it and make any required changes (even pull request, if you like). Maybe other forks already includes an update or fix you’re looking for.

P.S. Also this module was developed as an experiment, on how I can implement an API client based on Requests. Far less experimental and ugly than my [PyMailgun](/Aeron/PyMailgun/) for sure, but still. If I were developing it now, it would hardly became the same… because of many reasons. So I think it’ll be better to use it purely as an inspiration to develop your own library. Especially since the Push API is simple and minimal. Probably, it would be even enough to use only Requests or any other HTTP library.
